# Lefthook Git Hooks Manager Main Config File
# For more information, see: https://lefthook.dev/configuration/
---
pre-commit:
  piped: true
  jobs:
    - name: format
      group:
        parallel: true
        jobs:
          - name: cmake-format
            run: cmake-format {staged_files} -i
            glob: "{*.cmake,CMakeLists.txt}"
            stage_fixed: true
    - name: lint
      group:
        parallel: true
        jobs:
          - name: cmake-lint
            run: cmake-lint {staged_files}
            glob: "{*.cmake,CMakeLists.txt}"
          - name: yamllint
            run: yamllint -s {staged_files}
            glob: "*.{yml,yaml}"
          - name: markdownlint
            run: markdownlint-cli2 {staged_files}
            glob: "*.md"
...
